"""
纯计算层 — 无副作用的数学函数

依赖方向: app/core/pure/ → app/core/ → app/services/ → app/api/
本模块只依赖 numpy/pandas，不依赖数据库、缓存、日志等外部资源。

模块:
- factor_math: 因子计算纯函数（动量、波动率、换手率等）
- risk_calc: 风险计算纯函数（IC、RankIC、波动率、最大回撤等）
- portfolio_opt: 组合优化纯函数（等权、IC加权、约束优化等）
- preprocess: 数据预处理纯函数（去极值、标准化、中性化等）
- cpcv: 组合清洗交叉验证（Combinatorial Purged Cross-Validation）
"""

from app.core.pure.cpcv import (
    CombinatorialPurgedCV,
    PurgedKFold,
    get_embargo_times,
    get_train_times,
)
from app.core.pure.factor_math import (
    calc_amihud_illiquidity,
    calc_bollinger_bands,
    calc_bollinger_position,
    calc_bp,
    calc_cash_flow_manipulation,
    calc_cfo_to_net_profit,
    calc_cfp_ttm,
    calc_current_ratio,
    calc_earnings_stability,
    calc_earnings_surprise,
    calc_ema,
    calc_ep_ttm,
    calc_eps_revision,
    calc_goodwill_ratio,
    calc_gross_profit_margin,
    calc_high_low_ratio,
    calc_intraday_return,
    calc_ipo_age,
    calc_large_order_ratio,
    calc_limit_up_down_ratio,
    calc_macd,
    calc_macd_signal,
    calc_margin_signal,
    calc_momentum,
    calc_momentum_skip,
    calc_net_profit_margin,
    calc_north_holding_change,
    calc_north_net_buy_ratio,
    calc_obv_ratio,
    calc_overnight_return,
    calc_price_volume_corr,
    calc_rating_upgrade_ratio,
    calc_reversal,
    calc_reversal_1m,
    calc_roa,
    calc_roe,
    calc_rsi,
    calc_size_momentum_interaction,
    calc_sloan_accrual,
    calc_smart_money_ratio,
    calc_sp_ttm,
    calc_turnover_mean,
    calc_turnover_ratio,
    calc_value_quality_interaction,
    calc_volatility,
    calc_volatility_annualized,
    calc_vpin,
    calc_yoy_growth,
    calc_zero_return_ratio,
    safe_divide,
    winsorize_mad,
    zscore_normalize,
)
from app.core.pure.portfolio_opt import (
    apply_lot_size_constraint,
    apply_position_limits,
    apply_turnover_constraint,
    equal_weight,
    ic_weighted,
)
from app.core.pure.preprocess import (
    align_direction,
    check_coverage,
    cross_sectional_residual,
    fill_missing_industry_mean,
    fill_missing_mean,
    fill_missing_median,
    fill_missing_zero,
    neutralize_industry,
    neutralize_market_cap,
    sanitize_dataframe,
    sanitize_series,
    standardize_minmax,
    standardize_rank,
    standardize_rank_normal,
    standardize_rank_zscore,
    standardize_robust_zscore,
    standardize_zscore,
    winsorize_mad as winsorize_mad_preprocess,
    winsorize_quantile,
    winsorize_sigma,
)
from app.core.pure.risk_calc import (
    calc_calmar_ratio,
    calc_cvar,
    calc_ic,
    calc_max_drawdown,
    calc_psi,
    calc_rank_ic,
    calc_rolling_ic,
    calc_sharpe_ratio,
    calc_sortino_ratio,
    calc_var,
)

__all__ = [
    # cpcv
    "CombinatorialPurgedCV",
    "PurgedKFold",
    "get_embargo_times",
    "get_train_times",
    # factor_math
    "calc_amihud_illiquidity",
    "calc_bollinger_bands",
    "calc_bollinger_position",
    "calc_bp",
    "calc_cash_flow_manipulation",
    "calc_cfo_to_net_profit",
    "calc_cfp_ttm",
    "calc_current_ratio",
    "calc_earnings_stability",
    "calc_earnings_surprise",
    "calc_ema",
    "calc_ep_ttm",
    "calc_eps_revision",
    "calc_goodwill_ratio",
    "calc_gross_profit_margin",
    "calc_high_low_ratio",
    "calc_intraday_return",
    "calc_ipo_age",
    "calc_large_order_ratio",
    "calc_limit_up_down_ratio",
    "calc_macd",
    "calc_macd_signal",
    "calc_margin_signal",
    "calc_momentum",
    "calc_momentum_skip",
    "calc_net_profit_margin",
    "calc_north_holding_change",
    "calc_north_net_buy_ratio",
    "calc_obv_ratio",
    "calc_overnight_return",
    "calc_price_volume_corr",
    "calc_rating_upgrade_ratio",
    "calc_reversal",
    "calc_reversal_1m",
    "calc_roa",
    "calc_roe",
    "calc_rsi",
    "calc_size_momentum_interaction",
    "calc_sloan_accrual",
    "calc_smart_money_ratio",
    "calc_sp_ttm",
    "calc_turnover_mean",
    "calc_turnover_ratio",
    "calc_value_quality_interaction",
    "calc_volatility",
    "calc_volatility_annualized",
    "calc_vpin",
    "calc_yoy_growth",
    "calc_zero_return_ratio",
    "safe_divide",
    "winsorize_mad",
    "zscore_normalize",
    # portfolio_opt
    "apply_lot_size_constraint",
    "apply_position_limits",
    "apply_turnover_constraint",
    "equal_weight",
    "ic_weighted",
    # preprocess
    "align_direction",
    "check_coverage",
    "cross_sectional_residual",
    "fill_missing_industry_mean",
    "fill_missing_mean",
    "fill_missing_median",
    "fill_missing_zero",
    "neutralize_industry",
    "neutralize_market_cap",
    "sanitize_dataframe",
    "sanitize_series",
    "standardize_minmax",
    "standardize_rank",
    "standardize_rank_normal",
    "standardize_rank_zscore",
    "standardize_robust_zscore",
    "standardize_zscore",
    "winsorize_mad_preprocess",
    "winsorize_quantile",
    "winsorize_sigma",
    # risk_calc
    "calc_calmar_ratio",
    "calc_cvar",
    "calc_ic",
    "calc_max_drawdown",
    "calc_psi",
    "calc_rank_ic",
    "calc_rolling_ic",
    "calc_sharpe_ratio",
    "calc_sortino_ratio",
    "calc_var",
]
